SELECT c.name, p.MONTH_COUNT
FROM (
    SELECT p.CLIENT_ID,
              MAX(EXTRACT(MONTH FROM p.FINISH_DATE) - EXTRACT(MONTH FROM p.START_DATE)) AS MONTH_COUNT
    FROM project p
    GROUP BY p.CLIENT_ID
    ORDER BY MONTH_COUNT DESC
    LIMIT 1
    ) AS p
    JOIN client c ON p.CLIENT_ID = c.id;
