SELECT COUNT(*) AS PROJECT_COUNT, C.name
FROM project P
JOIN CLIENT C ON P.CLIENT_ID = C.ID
GROUP BY P.CLIENT_ID, C.name
HAVING COUNT(*) = (
    SELECT MAX(PROJECT_COUNT)
    FROM (
        SELECT CLIENT_ID, COUNT(*) AS PROJECT_COUNT
        FROM project
        GROUP BY CLIENT_ID
    ) AS temp
);
